# Generated by Django 5.1.3 on 2024-11-21 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rool_no',
            new_name='roll_no',
        ),
    ]
